### ISSUE TITLE
Downloader script is not fault tolerant and has too many hard coded links

### ISSUE THREAD

**Issue by alexandredias3d** [dnatividade/trainings#1]
The `download-VMs.sh` script downloads all parts of the tar file without checking for errors. This way, the script will not try to download parts which could not be successfully downloaded.

The script size can be reduced by using for loops to reduce the amount of hard-coded links and improve readability.

The code below summarizes these two improvements to the `download-VMs.sh` script.

```shell
# Download first part (from a to f there are a to z elements)
for i in {a..f}
do
    for j in {a..z}
    do
        URL="${ROOT_URL}${i}${j}"
        ret=$(wget --no-check-certificate "${URL}")
        while [ $ret -ne 0 ]
        do
            ret=$(wget --no-check-certificate "${URL}")
        done
    done
done

# Download second part (g has elements from a to g)
for i in {a..g}
do
    URL="${ROOT_URL}g${i}"
    ret=$(wget --no-check-certificate "${URL}")
    while [ $ret -ne 0 ]
    do
        ret=$(wget --no-check-certificate "${URL}")
    done
done
```

The script can be further improved if `wget` is wrapped in a user-defined function with different settings of timeouts. The output from `wget` could be filtered to show only the progress bar for each part being download. Also, the script could show how many parts have been downloaded.

**Comment by dnatividade** [comment]
Thank you Alexandre The Great. 
I'll do it!
